#!/bin/bash
## wget --no-check-certificate raw.github.com/toekang/tap2td/master/tap2td; chmod 100 tap2td; ./tap2td
## Enter [q] to quit, no warranty to any damage on your system, proceed at your own risk.
if [ $USER != 'root' ]; then echo "Run as root"; sleep 2; exit; fi; if [ ! -f /etc/debian_version ]; then echo "Debian 6-7 only."; sleep 2; exit; fi; function p_i { echo; echo -e "\033[1;37m$1
"; }; echo "$(grep address /etc/network/interfaces | grep -v 127.0.0.1  | awk '{print $2}' | grep -q '.' | head -1)"; 
IP=$(grep address /etc/network/interfaces | grep -v 127.0.0.1  | awk '{print $2}' | grep '.' | head -1); p_i ""; 
clear; echo "################################################################################"; echo "#            Apache2 & Transmission-Daemon Quick \
Installer Script.             #"; echo "#      No warranty to any damage on your system, proceed at your own risk.     #"; echo "##############################################################\
##################"; p_i ""; echo "   1) Un|Install Apache2 & Transmission-Daemon"; p_i "   0) Script info ./tap2td"; read -p "  Select an option [0-1]|[ctrl+c]: " -n 1 -r option; cas\
e $option in 1)if [ -e /etc/transmission-daemon/settings.json ]; then echo ") Already installed"; echo; read -p "  Uninstall Apache2 & Transmission-Daemon? [y/n]: " -n 1 -r; if [[ $REPLY =~ ^\
[Yy]$ ]]; then echo; service apache2 stop; service transmission-daemon stop; apt-get remove --purge apache2\* transmission-daemon\* -y; dpkg -l | grep -i apache2 transmission-daemon; apt-get \
clean all; apt-get autoremove -y; rm -rf ~/downloads /etc/apache2; p_i "  Done Uninstalling Apache2 & Transmission-Daemon"; sleep 2; ./tap2td; else echo ") Aborting .."; sleep 2; ./tap2td; fi
fi; read -p ") Enter Apache2 port e.g.: " -e -i 909 PORT; echo; read -p "  Enter Transmission-Daemon port e.g.: " -e -i 9090 PORTT; apt-get update; apt-get install apache2 transmission-daemon\
 -y; apt-get remove --purge minissdpd\* -y; dpkg -l | grep -i minissdpd; apt-get clean; apt-get autoremove -y; rm -rf /etc/apache2/ports.conf /etc/apache2/sites-enabled/000-default /etc/trans\
mission-daemon/settings.json; cat > /etc/apache2/ports.conf <<END
NameVirtualHost *:$PORT
Listen $PORT
END
cat > /etc/apache2/sites-enabled/transmission-daemon <<END
<VirtualHost *:$PORT>
	ServerAdmin webmaster@localhost

	DocumentRoot /var/lib/transmission-daemon/downloads/
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>
	<Directory /var/lib/transmission-daemon/downloads/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>

	ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
	<Directory "/usr/lib/cgi-bin">
		AllowOverride None
		Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
		Order allow,deny
		Allow from all
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
END
chmod 555 /etc/apache2/sites-enabled/transmission-daemon; cat > /etc/transmission-daemon/settings.json <<END
{
    "alt-speed-down": 50, 
    "alt-speed-enabled": false, 
    "alt-speed-time-begin": 540, 
    "alt-speed-time-day": 127, 
    "alt-speed-time-enabled": false, 
    "alt-speed-time-end": 1020, 
    "alt-speed-up": 50, 
    "bind-address-ipv4": "0.0.0.0", 
    "bind-address-ipv6": "::", 
    "blocklist-enabled": false, 
    "blocklist-url": "http://www.example.com/blocklist", 
    "cache-size-mb": 4, 
    "dht-enabled": true, 
    "download-dir": "/var/lib/transmission-daemon/downloads", 
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "download-queue-enabled": true, 
    "download-queue-size": 5, 
    "encryption": 1, 
    "idle-seeding-limit": 30, 
    "idle-seeding-limit-enabled": false, 
    "incomplete-dir": "/root/Downloads", 
    "incomplete-dir-enabled": false, 
    "lpd-enabled": false, 
    "max-peers-global": 200, 
    "message-level": 2, 
    "peer-congestion-algorithm": "", 
    "peer-limit-global": 240, 
    "peer-limit-per-torrent": 60, 
    "peer-port": 51413, 
    "peer-port-random-high": 65535, 
    "peer-port-random-low": 49152, 
    "peer-port-random-on-start": false, 
    "peer-socket-tos": "default", 
    "pex-enabled": true, 
    "port-forwarding-enabled": false, 
    "preallocation": 1, 
    "prefetch-enabled": 1, 
    "queue-stalled-enabled": true, 
    "queue-stalled-minutes": 30, 
    "ratio-limit": 2, 
    "ratio-limit-enabled": false, 
    "rename-partial-files": true, 
    "rpc-authentication-required": true, 
    "rpc-bind-address": "0.0.0.0", 
    "rpc-enabled": true, 
    "rpc-password": "$PORTT", 
    "rpc-port": $PORTT, 
    "rpc-url": "/transmission/", 
    "rpc-username": "$PORT", 
    "rpc-whitelist": "*", 
    "rpc-whitelist-enabled": true, 
    "scrape-paused-torrents-enabled": true, 
    "script-torrent-done-enabled": false, 
    "script-torrent-done-filename": "", 
    "seed-queue-enabled": false, 
    "seed-queue-size": 10, 
    "speed-limit-down": 100, 
    "speed-limit-down-enabled": false, 
    "speed-limit-up": 40, 
    "speed-limit-up-enabled": true, 
    "start-added-torrents": true, 
    "trash-original-torrent-files": true, 
    "umask": 18, 
    "upload-limit": 100, 
    "upload-limit-enabled": 0, 
    "upload-slots-per-torrent": 14, 
    "utp-enabled": true
}
END
chmod 555 /etc/transmission-daemon/settings.json; cd /etc/transmission-daemon; chmod 600 settings.json; chown debian-transmission:debian-transmission settings.json; cd ~; ln -s /var/lib/trans\
mission-daemon/downloads; service apache2 restart; service transmission-daemon reload; echo; echo "  Done, Apache2 & Transmission-Daemon installed."; echo  "  Apache2 running at $IP:$PORT"
echo "  Transmission-Daemon running at $IP:$PORTT"; echo "  Authentication: $PORT|$PORTT"; echo; read -p  "  Back to main [enter]: "; cd ~; ./tap2td;; 0)apt-get install less -y; cat ~/tap2td \
| less; ./tap2td;; esac; echo "  Can't find that option .."; sleep 3; ./tap2td done
